"""The scratch lease (single occupant, re-entrant, heartbeat + stale-expiry reclaim) and
retention: delete a job's scratch directory on success, and bound total on-disk scratch
usage with an oldest-first eviction ceiling.

The lease is acquirable and releasable independently of the worker loop by design: callers
pass their own `session_factory` (an `async_sessionmaker`), not a live worker instance, so
"a second job waits for the lease" is a property of this module alone.
"""

import asyncio
import logging
import shutil
import uuid
from collections.abc import Callable
from datetime import UTC, datetime, timedelta
from pathlib import Path

from sqlalchemy import func, select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

from uadclaw.models import Job, JobState, ScratchLease, ScratchLeaseEvent

logger = logging.getLogger(__name__)

SessionFactory = Callable[[], AsyncSession]

_LEASE_ROW_ID = 1

# Arbitrary fixed key for the session-level advisory lock serializing retention sweeps
# across concurrent callers (a periodic sweep task and a just-failed job's own cleanup can
# otherwise race, each seeing a different partial view of "what's on disk" under
# SKIP LOCKED and both under-evict). Fits a signed bigint; value has no meaning beyond
# being stable and unlikely to collide with an unrelated advisory lock in this database.
_RETENTION_SWEEP_LOCK_KEY = 0x75616463_6C617721


class ScratchLeaseTimeout(RuntimeError):
    """Raised when `acquire_scratch_lease` is given a timeout and it elapses before the
    lease frees up. Distinct type so callers can tell "still contended" from a bug."""


def _utcnow() -> datetime:
    return datetime.now(UTC)


async def _ensure_lease_row(session: AsyncSession) -> None:
    """Lazily seed the singleton lease row. Kept out of the migration so the migration
    stays pure schema, autogenerated from `Base.metadata` rather than hand-written.

    `INSERT ... ON CONFLICT DO NOTHING`, not a `get`-then-`add`: two workers can both hit
    an empty table on their first-ever lease attempt, and a plain check-then-insert races
    them into the same unique-key violation `_try_acquire_once`'s `FOR UPDATE` is supposed
    to prevent further down.
    """
    stmt = (
        pg_insert(ScratchLease)
        .values(id=_LEASE_ROW_ID)
        .on_conflict_do_nothing(index_elements=[ScratchLease.id])
    )
    await session.execute(stmt)


async def _try_acquire_once(
    session: AsyncSession, *, job_id: uuid.UUID, worker_id: str, stale_after: timedelta
) -> bool:
    await _ensure_lease_row(session)
    lease = (
        await session.execute(
            select(ScratchLease).where(ScratchLease.id == _LEASE_ROW_ID).with_for_update()
        )
    ).scalar_one()

    now = _utcnow()

    # Re-entrant: a job that already holds the lease under its OWN worker identity (e.g. a
    # stage handler calls acquire defensively on top of the one `_run_job` already did)
    # must not wait out the stale window for a lease it already owns. Job id alone is not
    # enough to key this on: after a reclaim, a NEW attempt under a NEW worker id claims
    # the SAME job id while the OLD worker may still show as the lease holder (job-level
    # reclaim does not touch the lease) — that must fall through to the staleness check
    # below and be reclaimed/logged normally, not silently "inherited" as if it were this
    # worker's own lease.
    if lease.holder_job_id == job_id and lease.holder_worker_id == worker_id:
        lease.heartbeat_at = now
        return True

    if lease.holder_job_id is not None and lease.heartbeat_at is not None:
        staleness = now - lease.heartbeat_at
        if staleness > stale_after:
            logger.warning(
                "reclaiming stale scratch lease: previous_holder_job=%s "
                "previous_holder_worker=%s stale_for=%s reclaiming_job=%s "
                "reclaiming_worker=%s",
                lease.holder_job_id,
                lease.holder_worker_id,
                staleness,
                job_id,
                worker_id,
            )
            session.add(
                ScratchLeaseEvent(
                    job_id=lease.holder_job_id,
                    worker_id=lease.holder_worker_id,
                    event="reclaimed",
                    at=now,
                    detail=f"stale_for_seconds={staleness.total_seconds():.3f}",
                )
            )
            lease.holder_job_id = None
            lease.holder_worker_id = None
            lease.acquired_at = None
            lease.heartbeat_at = None

    if lease.holder_job_id is not None:
        return False

    lease.holder_job_id = job_id
    lease.holder_worker_id = worker_id
    lease.acquired_at = now
    lease.heartbeat_at = now
    session.add(ScratchLeaseEvent(job_id=job_id, worker_id=worker_id, event="acquired", at=now))
    return True


async def acquire_scratch_lease(
    session_factory: SessionFactory,
    *,
    job_id: uuid.UUID,
    worker_id: str,
    stale_after: timedelta,
    poll_interval: float = 0.2,
    timeout: float | None = None,
) -> None:
    """Block (polling `poll_interval` apart) until this job holds the sole scratch lease,
    reclaiming a stale holder along the way. Re-entrant: a job that already holds the
    lease returns immediately. Raises `ScratchLeaseTimeout` if `timeout` is given and
    elapses first.
    """
    async with session_factory() as session, session.begin():
        session.add(
            ScratchLeaseEvent(job_id=job_id, worker_id=worker_id, event="requested", at=_utcnow())
        )

    deadline = _utcnow() + timedelta(seconds=timeout) if timeout is not None else None
    while True:
        async with session_factory() as session, session.begin():
            acquired = await _try_acquire_once(
                session, job_id=job_id, worker_id=worker_id, stale_after=stale_after
            )
        if acquired:
            return
        if deadline is not None and _utcnow() >= deadline:
            raise ScratchLeaseTimeout(
                f"acquire_scratch_lease: job {job_id} did not acquire the scratch lease "
                f"within {timeout}s; scratch is held by another job"
            )
        await asyncio.sleep(poll_interval)


async def release_scratch_lease(
    session_factory: SessionFactory, *, job_id: uuid.UUID, worker_id: str
) -> None:
    """No-op (logged) unless the caller is the CURRENT holder by both job id and worker
    id: a fenced-out worker that thinks it still owns job J must not release a lease a
    newer attempt (running under a different worker id) has since acquired for the same
    job id."""
    async with session_factory() as session, session.begin():
        lease = (
            await session.execute(
                select(ScratchLease).where(ScratchLease.id == _LEASE_ROW_ID).with_for_update()
            )
        ).scalar_one_or_none()
        if lease is None or lease.holder_job_id != job_id or lease.holder_worker_id != worker_id:
            logger.warning(
                "release_scratch_lease: job=%s worker=%s asked to release a lease it does "
                "not hold (current holder job=%s worker=%s); ignoring",
                job_id,
                worker_id,
                lease.holder_job_id if lease else None,
                lease.holder_worker_id if lease else None,
            )
            return
        now = _utcnow()
        lease.holder_job_id = None
        lease.holder_worker_id = None
        lease.acquired_at = None
        lease.heartbeat_at = None
        session.add(ScratchLeaseEvent(job_id=job_id, worker_id=worker_id, event="released", at=now))


async def heartbeat_scratch_lease(
    session_factory: SessionFactory, *, job_id: uuid.UUID, worker_id: str
) -> bool:
    async with session_factory() as session, session.begin():
        lease = (
            await session.execute(
                select(ScratchLease).where(ScratchLease.id == _LEASE_ROW_ID).with_for_update()
            )
        ).scalar_one_or_none()
        if (
            lease is not None
            and lease.holder_job_id == job_id
            and lease.holder_worker_id == worker_id
        ):
            lease.heartbeat_at = _utcnow()
            return True
        return False


# --- Scratch directories: keyed on (job_id, attempt), not job_id alone. -----------------
#
# A job reclaimed out from under a still-alive worker (M3/M4) restarts as a new attempt
# under a new worker id; if the two attempts wrote into the SAME directory, the old
# (fenced-out) attempt's `rmtree` on success would delete files the new attempt is still
# writing. Keying on attempt as well makes that structurally impossible: fencing stops the
# old attempt's DB writes, and even if it somehow raced past that, it would only ever touch
# its OWN attempt's directory.


def job_scratch_dir(scratch_root: Path, job_id: uuid.UUID, attempt: int) -> Path:
    return scratch_root / f"{job_id}-{attempt}"


def _parse_scratch_dir_name(name: str) -> tuple[uuid.UUID, int] | None:
    try:
        job_id_str, attempt_str = name.rsplit("-", 1)
        return uuid.UUID(job_id_str), int(attempt_str)
    except (ValueError, AttributeError):
        return None


async def prepare_scratch_dir(scratch_root: Path, job_id: uuid.UUID, attempt: int) -> Path:
    path = job_scratch_dir(scratch_root, job_id, attempt)
    await asyncio.to_thread(path.mkdir, parents=True, exist_ok=True)
    return path


def _iter_file_sizes(root: Path):
    """Every regular file's size under `root`, TOCTOU-safe and symlink-aware.

    `is_file()` already swallows a vanished-file `OSError` internally and returns False,
    but the `.stat()` call that follows it is a second, separate syscall — a file can
    disappear between the two (firmware unpack tooling deletes temp files as it goes), and
    an uncaught `OSError` there would crash the whole retention sweep over one race. A
    symlink is skipped rather than sized via its target: `stat()` follows symlinks but
    `rmtree` does not, so counting a symlink's target bytes bills space eviction can never
    actually free, and once real firmware (which does contain symlinks) lands in task 3
    that mismatch turns into an eviction loop that never converges.
    """
    for f in root.rglob("*"):
        if f.is_symlink():
            continue
        if not f.is_file():
            continue
        try:
            yield f.stat().st_size
        except OSError:
            continue


async def _dir_size_bytes(path: Path) -> int:
    def _walk() -> int:
        if not path.exists():
            return 0
        return sum(_iter_file_sizes(path))

    return await asyncio.to_thread(_walk)


async def _rmtree(path: Path) -> None:
    def _remove() -> None:
        if path.exists():
            shutil.rmtree(path)

    await asyncio.to_thread(_remove)


async def cleanup_scratch_dir(scratch_root: Path, job_id: uuid.UUID, attempt: int) -> None:
    """Retention on success: delete this attempt's scratch directory (the firmware archive
    plus every extracted APK). Caller commits the SUCCEEDED state in its own transaction
    first — see `worker.py` — so a cleanup failure here never rolls back a job that
    genuinely finished every stage of its kind back into looking FAILED."""
    await _rmtree(job_scratch_dir(scratch_root, job_id, attempt))


# --- Retention ceiling: bounds actual disk usage under scratch_root, not just FAILED-job
# rows. A success whose rmtree partly failed, a crashed job sitting QUEUED again under a
# new attempt, and a directory with no matching job row at all are all real bytes on disk
# that a ceiling keyed only on `state == FAILED` would never see. --------------------------


def _is_live(job_state: JobState | None, job_attempt: int | None, dir_attempt: int) -> bool:
    """A directory is still actively owned — must NOT be evicted — only when it belongs to
    the job's CURRENT attempt and that job is not yet in a terminal state."""
    if job_state is None:
        return False  # no job row at all: orphaned, evictable
    if job_attempt != dir_attempt:
        return False  # superseded attempt: evictable
    return job_state in (JobState.QUEUED, JobState.CLAIMED, JobState.RUNNING)


def _scan_evictable_dirs(
    scratch_root: Path, live_identity: dict[uuid.UUID, tuple[JobState, int]]
) -> list[tuple[Path, float, int, uuid.UUID, int]]:
    """Sync (thread-offloaded) filesystem walk: every PROVISIONALLY evictable directory
    under `scratch_root` as (path, mtime, size_bytes, job_id, dir_attempt). No DB access
    here — the DB read that produced `live_identity` already happened and committed before
    this runs, and this walk itself can take seconds on a large tree, so `live_identity`
    can be stale by the time any individual entry is actually deleted. Every entry this
    returns gets re-checked against CURRENT state immediately before deletion — see
    `_is_still_evictable` — so a false "not live at scan time" here only risks a wasted
    re-check, never a wrongful delete."""
    if not scratch_root.exists():
        return []
    entries: list[tuple[Path, float, int, uuid.UUID, int]] = []
    for child in scratch_root.iterdir():
        if not child.is_dir():
            continue
        parsed = _parse_scratch_dir_name(child.name)
        if parsed is None:
            continue  # not one of ours; leave it alone
        job_id, dir_attempt = parsed
        state, attempt = live_identity.get(job_id, (None, None))
        if _is_live(state, attempt, dir_attempt):
            continue
        try:
            mtime = child.stat().st_mtime
        except OSError:
            continue  # vanished between iterdir() and stat()
        size = sum(_iter_file_sizes(child))
        entries.append((child, mtime, size, job_id, dir_attempt))
    return entries


async def _is_still_evictable(
    session_factory: SessionFactory, job_id: uuid.UUID, dir_attempt: int
) -> bool:
    """Re-read this job's CURRENT (state, attempt) immediately before deleting its
    directory. The scan's `live_identity` snapshot is read once, before a filesystem walk
    that can run for seconds on a large scratch tree — long enough for a slot to claim this
    exact job, bump its attempt, and start writing into a NEW directory while this one sits
    in the eviction queue looking stale. A delete decision has to be made against current
    state, not a snapshot that predates the walk."""
    async with session_factory() as session:
        row = (
            await session.execute(select(Job.state, Job.attempt).where(Job.id == job_id))
        ).one_or_none()
    state, attempt = row if row is not None else (None, None)
    return not _is_live(state, attempt, dir_attempt)


async def _do_enforce_retention_ceiling(
    session_factory: SessionFactory, scratch_root: Path, *, ceiling_bytes: int
) -> list[str]:
    # Step 1: a quick, short-lived read — no row locks, no long-held transaction spanning
    # the filesystem walk below.
    async with session_factory() as session:
        rows = (await session.execute(select(Job.id, Job.state, Job.attempt))).all()
    live_identity = {job_id: (state, attempt) for job_id, state, attempt in rows}

    # Step 2: the filesystem walk, entirely outside any DB transaction.
    entries = await asyncio.to_thread(_scan_evictable_dirs, scratch_root, live_identity)
    entries.sort(key=lambda e: e[1])  # oldest mtime first

    total = sum(size for _, _, size, _, _ in entries)
    evicted: list[str] = []
    idx = 0
    while total > ceiling_bytes and idx < len(entries):
        path, _mtime, freed, job_id, dir_attempt = entries[idx]
        idx += 1
        if not await _is_still_evictable(session_factory, job_id, dir_attempt):
            logger.info(
                "retention sweep: %s went live between the walk and eviction; leaving it",
                path.name,
            )
            continue
        await _rmtree(path)
        total -= freed
        evicted.append(path.name)
        logger.warning(
            "evicting scratch artifacts: dir=%s freed_bytes=%d remaining_total_bytes=%d "
            "ceiling_bytes=%d",
            path.name,
            freed,
            total,
            ceiling_bytes,
        )

    # Step 3: a short transaction per eviction that still has a matching job row, so
    # `artifacts_deleted_at` reflects reality. Orphaned/superseded-attempt directories with
    # no matching row have nothing to update.
    if evicted:
        evicted_job_ids = {
            job_id
            for name in evicted
            if (parsed := _parse_scratch_dir_name(name)) is not None
            for job_id in [parsed[0]]
            if job_id in live_identity
        }
        if evicted_job_ids:
            now = _utcnow()
            async with session_factory() as session, session.begin():
                jobs = (
                    await session.execute(select(Job).where(Job.id.in_(evicted_job_ids)))
                ).scalars()
                for job in jobs:
                    job.artifacts_deleted_at = now

    return evicted


async def enforce_retention_ceiling(
    session_factory: SessionFactory, scratch_root: Path, *, ceiling_bytes: int
) -> list[str]:
    """Total bytes of scratch on disk that is no longer actively owned, oldest-mtime-first
    eviction: while the sum exceeds `ceiling_bytes`, delete the oldest such directory and
    keep going until the total fits or nothing evictable is left. Returns the evicted
    directory names, oldest first.

    Serialized cluster-wide via a session-level Postgres advisory lock: a periodic sweep
    and a just-failed job's own cleanup can otherwise both read "what's on disk" from a
    stale, pre-eviction view and each independently decide the ceiling is still exceeded,
    each evicting less than the other assumed — a session-level lock (not `_xact`, so it
    covers the deliberately-transaction-free filesystem walk in step 2 above) makes that
    structurally impossible rather than hoping the next periodic pass corrects it.
    """
    async with session_factory() as lock_session:
        got_lock = (
            await lock_session.execute(select(func.pg_try_advisory_lock(_RETENTION_SWEEP_LOCK_KEY)))
        ).scalar_one()
        if not got_lock:
            logger.info("retention sweep already in progress elsewhere; skipping this pass")
            return []
        # Nothing here needs a data transaction; end the implicit one autobegin opened so
        # this connection doesn't sit idle-in-transaction for the walk's duration.
        await lock_session.commit()
        try:
            return await _do_enforce_retention_ceiling(
                session_factory, scratch_root, ceiling_bytes=ceiling_bytes
            )
        finally:
            await lock_session.execute(select(func.pg_advisory_unlock(_RETENTION_SWEEP_LOCK_KEY)))
            await lock_session.commit()
