"""add package_classification

Revision ID: 1574d86cdd95
Revises: 30c4816234b6
Create Date: 2026-08-11 20:36:02.856588

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1574d86cdd95"
down_revision: str | Sequence[str] | None = "30c4816234b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_classification",
        sa.Column("package", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bundle_sha256", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("thinking", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uad_list", sa.String(length=16), nullable=True),
        sa.Column("removal", sa.String(length=16), nullable=True),
        sa.Column("confidence", sa.String(length=16), nullable=True),
        sa.Column(
            "unknown_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("reasoning_brief", sa.Text(), nullable=True),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "usage",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("parked", sa.Boolean(), nullable=False),
        sa.Column("parked_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("package"),
    )
    op.create_index(
        "ix_package_classification_bundle_sha256",
        "package_classification",
        ["bundle_sha256"],
        unique=False,
    )
    op.create_index(
        "ix_package_classification_parked", "package_classification", ["parked"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_package_classification_parked", table_name="package_classification")
    op.drop_index("ix_package_classification_bundle_sha256", table_name="package_classification")
    op.drop_table("package_classification")
    # ### end Alembic commands ###
