"""add corpus graph, filter and rule ladder tables

Revision ID: 30c4816234b6
Revises: fe79b328d598
Create Date: 2026-08-11 16:38:39.437389

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30c4816234b6"
down_revision: str | Sequence[str] | None = "fe79b328d598"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_analysis",
        sa.Column("package", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "dependencies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "needed_by",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "edges",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("upstream_present", sa.Boolean(), nullable=True),
        sa.Column("queued", sa.Boolean(), nullable=True),
        sa.Column("filter_verdict", sa.String(length=32), nullable=True),
        sa.Column("upstream_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("floor", sa.String(length=16), nullable=True),
        sa.Column("floor_rule", sa.String(length=32), nullable=True),
        sa.Column(
            "floor_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("privapp_allowlisted", sa.Boolean(), nullable=True),
        sa.Column("privapp_permission_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("package"),
    )
    op.create_index("ix_package_analysis_floor", "package_analysis", ["floor"], unique=False)
    op.create_index("ix_package_analysis_queued", "package_analysis", ["queued"], unique=False)
    op.add_column(
        "device_scans",
        sa.Column(
            "config_inputs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.create_index("ix_device_scans_job_id", "device_scans", ["job_id"], unique=False)
    op.add_column(
        "package_facts",
        sa.Column(
            "queries_packages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "package_observations",
        sa.Column(
            "queries_packages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("package_observations", "queries_packages")
    op.drop_column("package_facts", "queries_packages")
    op.drop_index("ix_device_scans_job_id", table_name="device_scans")
    op.drop_column("device_scans", "config_inputs")
    op.drop_index("ix_package_analysis_queued", table_name="package_analysis")
    op.drop_index("ix_package_analysis_floor", table_name="package_analysis")
    op.drop_table("package_analysis")
    # ### end Alembic commands ###
