"""add package icons

Revision ID: 37b785e1bcb4
Revises: b6cd610e7a14
Create Date: 2026-08-12 21:00:49.447377

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37b785e1bcb4"
down_revision: str | Sequence[str] | None = "b6cd610e7a14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("package_facts", sa.Column("icon_bytes", sa.LargeBinary(), nullable=True))
    op.add_column("package_facts", sa.Column("icon_mime", sa.String(length=32), nullable=True))
    op.add_column("package_observations", sa.Column("icon_bytes", sa.LargeBinary(), nullable=True))
    op.add_column(
        "package_observations", sa.Column("icon_mime", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("package_observations", "icon_mime")
    op.drop_column("package_observations", "icon_bytes")
    op.drop_column("package_facts", "icon_mime")
    op.drop_column("package_facts", "icon_bytes")
    # ### end Alembic commands ###
