"""add branch emission tables

Revision ID: 60bbce12a008
Revises: 9c1e4f7a2b30
Create Date: 2026-08-13 09:36:16.002662

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60bbce12a008"
down_revision: str | Sequence[str] | None = "9c1e4f7a2b30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branch_emission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("vendor", sa.String(length=64), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("repo_path", sa.Text(), nullable=False),
        sa.Column("list_path", sa.Text(), nullable=False),
        sa.Column("base_commit", sa.String(length=64), nullable=False),
        sa.Column("list_sha256", sa.String(length=64), nullable=False),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column("pipeline_commit_sha", sa.String(length=64), nullable=False),
        sa.Column("package_count", sa.Integer(), nullable=False),
        sa.Column("pr_body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("commit_oid", sa.String(length=64), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciled", sa.Boolean(), nullable=False),
        # The recovery path reads `commit_oid IS NULL` as "this emission's outcome is not
        # known yet", so a half-written outcome is what would make it answer wrongly — and
        # answering wrongly there ends in a second branch on somebody's clone. Held in the
        # schema for the reason the icon pair is: a future writer touching one column cannot
        # reach around a CHECK.
        sa.CheckConstraint(
            "(commit_oid IS NULL) = (committed_at IS NULL)",
            name="ck_branch_emission_commit_pair",
        ),
        sa.CheckConstraint(
            "NOT reconciled OR commit_oid IS NOT NULL",
            name="ck_branch_emission_reconciled_commit",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", name="uq_branch_emission_job_id"),
    )
    op.create_index("ix_branch_emission_vendor", "branch_emission", ["vendor"], unique=False)
    op.create_table(
        "branch_emission_package",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("emission_id", sa.Integer(), nullable=False),
        sa.Column("package", sa.String(length=255), nullable=False),
        sa.Column("bundle_sha256", sa.String(length=64), nullable=False),
        sa.Column("uad_list", sa.String(length=16), nullable=False),
        sa.Column("removal", sa.String(length=16), nullable=False),
        sa.Column("floor", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["emission_id"], ["branch_emission.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("emission_id", "package", name="uq_branch_emission_package"),
    )
    op.create_index(
        "ix_branch_emission_package_package", "branch_emission_package", ["package"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_branch_emission_package_package", table_name="branch_emission_package")
    op.drop_table("branch_emission_package")
    op.drop_index("ix_branch_emission_vendor", table_name="branch_emission")
    op.drop_table("branch_emission")
    # ### end Alembic commands ###
