"""add corroboration tables

Revision ID: 6ccbc750a3b2
Revises: 1574d86cdd95
Create Date: 2026-08-12 14:36:05.554026

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ccbc750a3b2"
down_revision: str | Sequence[str] | None = "1574d86cdd95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_corroboration",
        sa.Column("package", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("thinking", sa.Boolean(), nullable=True),
        sa.Column(
            "sources",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "usage",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("package"),
    )
    op.create_index(
        "ix_package_corroboration_description_sha256",
        "package_corroboration",
        ["description_sha256"],
        unique=False,
    )
    op.create_index(
        "ix_package_corroboration_status", "package_corroboration", ["status"], unique=False
    )
    op.create_table(
        "package_search_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("package", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("block", sa.String(length=16), nullable=False),
        sa.Column("page_text", sa.Text(), nullable=True),
        sa.Column("fetch_error", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("package", "url", name="uq_package_search_results_url"),
    )
    op.create_index(
        "ix_package_search_results_package", "package_search_results", ["package"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_package_search_results_package", table_name="package_search_results")
    op.drop_table("package_search_results")
    op.drop_index("ix_package_corroboration_status", table_name="package_corroboration")
    op.drop_index("ix_package_corroboration_description_sha256", table_name="package_corroboration")
    op.drop_table("package_corroboration")
    # ### end Alembic commands ###
