"""add the triage decision log

Revision ID: b6cd610e7a14
Revises: 6ccbc750a3b2
Create Date: 2026-08-12 18:04:31.170919

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b6cd610e7a14"
down_revision: str | Sequence[str] | None = "6ccbc750a3b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_triage_decision",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("package", sa.String(length=255), nullable=False),
        sa.Column("bundle_sha256", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "edited_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        # A rejection with no reason is the row nobody can learn anything from, and the log
        # exists to be learned from. Held in the schema as well as in `triagestore` so a
        # future writer cannot reach the table around the check.
        sa.CheckConstraint(
            "action <> 'reject' OR (reason IS NOT NULL AND btrim(reason) <> '')",
            name="ck_package_triage_decision_reject_reason",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_package_triage_decision_package_decided_at",
        "package_triage_decision",
        ["package", "decided_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_package_triage_decision_package_decided_at", table_name="package_triage_decision"
    )
    op.drop_table("package_triage_decision")
    # ### end Alembic commands ###
