"""add job model and scratch lease

Revision ID: c81833d0cc73
Revises: 3940f22da1c9
Create Date: 2026-08-11 11:43:20.236431

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c81833d0cc73"
down_revision: str | Sequence[str] | None = "3940f22da1c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum("queued", "claimed", "running", "succeeded", "failed", name="job_state"),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=255), nullable=True),
        sa.Column("log_tail", sa.Text(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("artifacts_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_state_created_at", "jobs", ["state", "created_at"], unique=False)
    op.create_index("ix_jobs_state_heartbeat_at", "jobs", ["state", "heartbeat_at"], unique=False)
    op.create_table(
        "job_stage_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_stage_runs_job_id", "job_stage_runs", ["job_id"], unique=False)
    op.create_table(
        "scratch_lease",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("holder_job_id", sa.UUID(), nullable=True),
        sa.Column("holder_worker_id", sa.String(length=255), nullable=True),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("id = 1", name="ck_scratch_lease_singleton"),
        sa.ForeignKeyConstraint(["holder_job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scratch_lease_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("worker_id", sa.String(length=255), nullable=True),
        sa.Column("event", sa.String(length=16), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_scratch_lease_events_at", "scratch_lease_events", ["at"], unique=False)
    op.create_index(
        "ix_scratch_lease_events_job_id", "scratch_lease_events", ["job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scratch_lease_events_job_id", table_name="scratch_lease_events")
    op.drop_index("ix_scratch_lease_events_at", table_name="scratch_lease_events")
    op.drop_table("scratch_lease_events")
    op.drop_table("scratch_lease")
    op.drop_index("ix_job_stage_runs_job_id", table_name="job_stage_runs")
    op.drop_table("job_stage_runs")
    op.drop_index("ix_jobs_state_heartbeat_at", table_name="jobs")
    op.drop_index("ix_jobs_state_created_at", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
